export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const CHANGE_QUANTITY_PRODUCT_IN_CART = 'CHANGE_QUANTITY_PRODUCT_IN_CART';
export const CHANGE_MASAGE = 'CHANGE_MASAGE';
export const CHANGE_DISCOUNT_IN_CART = 'CHANGE_DISCOUNT_IN_CART';
export const DISCOUNT_IS_SELECT_IN_CART = 'DISCOUNT_IS_SELECT_IN_CART';
export const ON_LOAD_PAGE_CART = 'ON_LOAD_PAGE_CART';
export const ON_LOAD_PRODUCT_IS_SELECT = 'ON_LOAD_PRODUCT_IS_SELECT';
export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const DELETE_PRODUCT_IN_WISH_LIST = "DELETE_PRODUCT_IN_WISH_LIST";
export const ON_LOAD_PROMOTION_ON_STATE = "ON_LOAD_PROMOTION_ON_STATE";
export const ON_SELECT_PAGE_PRODUCT = "ON_SELECT_PAGE_PRODUCT";
export const PAGING_PRODUCT = "PAGING_PRODUCT";


export const LOAD_DATA_BRAND_FROM_API = 'LOAD_DATA_BRAND_FROM_API';
export const LOAD_DATA_CATEGORY_FROM_API = 'LOAD_DATA_CATEGORY_FROM_API';
export const LOAD_DATA_GROUP_FROM_API = 'LOAD_DATA_GROUP_FROM_API';
