export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const CHANGE_QUANTITY_PRODUCT_IN_CART = 'CHANGE_QUANTITY_PRODUCT_IN_CART';
export const CHANGE_MASAGE = 'CHANGE_MASAGE';
export const CHANGE_DISCOUNT_IN_CART = 'CHANGE_DISCOUNT_IN_CART';
export const ON_LOAD_PAGE_CART = 'ON_LOAD_PAGE_CART';
export const ON_LOAD_PRODUCT_IS_SELECT = 'ON_LOAD_PRODUCT_IS_SELECT';