export const FILTER_BEST_PROMOTION = 'FILTER_BEST_PROMOTION';
export const FILTER_BEST_SELLER = 'FILTER_BEST_SELLER';
export const FILTER_PRICE_INCREASE = 'FILTER_PRICE_INCREASES';
export const FILTER_PRICE_DECREASE = 'FILTER_PRICE_DECREASE';
export const FILTER_LOWEST_PRICE_TO_HIGHEST_PRICE = 'FILTER_LOWEST_PRICE_TO_HIGHEST_PRICE';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';