export const LOAD_DATA_PRODUCT_FROM_API = 'LOAD_DATA_PRODUCT_FROM_API'
export const SELECT_SIZE_ON_PRODUCT = 'SELECT_SIZE_ON_PRODUCT'
export const SELECT_IMAGE_SHOW_TO_PRODUCT_DETAIL = 'SELECT_IMAGE_SHOW_TO_PRODUCT_DETAIL'