export const ADD_PRODUCT_TO_IMPORTS = 'ADD_PRODUCT_TO_IMPORTS';
export const DELETE_PRODUCT_IN_iMPORTS = 'DELETE_PRODUCT_IN_iMPORTS'        //IMPORT LÀ HÓA ĐƠN NHẬP HÀNG
export const ADD_PRODUCT_SIZE_TO_IMPORT = 'PRODUCT_SIZE'
export const DELETE_PRODUCT_SIZE_IN_IMPORT = 'DELETE_PRODUCT_SIZE_IN_IMPORT'