var initialDistrict = [{"_id":"001","_name":"Ba Đình","_prefix":"Quận","_province_id":"01"}, 
{"_id":"002","_name":"Hoàn Kiếm","_prefix":"Quận","_province_id":"01"}, 
{"_id":"003","_name":"Tây Hồ","_prefix":"Quận","_province_id":"01"}, 
{"_id":"004","_name":"Long Biên","_prefix":"Quận","_province_id":"01"}, 
{"_id":"005","_name":"Cầu Giấy","_prefix":"Quận","_province_id":"01"}, 
{"_id":"006","_name":"Đống Đa","_prefix":"Quận","_province_id":"01"}, 
{"_id":"007","_name":"Hai Bà Trưng","_prefix":"Quận","_province_id":"01"}, 
{"_id":"008","_name":"Hoàng Mai","_prefix":"Quận","_province_id":"01"}, 
{"_id":"009","_name":"Thanh Xuân","_prefix":"Quận","_province_id":"01"}, 
{"_id":"016","_name":"Sóc Sơn","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"017","_name":"Đông Anh","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"018","_name":"Gia Lâm","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"019","_name":"Nam Từ Liêm","_prefix":"Quận","_province_id":"01"}, 
{"_id":"020","_name":"Thanh Trì","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"021","_name":"Bắc Từ Liêm","_prefix":"Quận","_province_id":"01"}, 
{"_id":"024","_name":"Hà Giang","_prefix":"Thành phố","_province_id":"02"}, 
{"_id":"026","_name":"Đồng Văn","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"027","_name":"Mèo Vạc","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"028","_name":"Yên Minh","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"029","_name":"Quản Bạ","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"030","_name":"Vị Xuyên","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"031","_name":"Bắc Mê","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"032","_name":"Hoàng Su Phì","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"033","_name":"Xín Mần","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"034","_name":"Bắc Quang","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"035","_name":"Quang Bình","_prefix":"Huyện","_province_id":"02"}, 
{"_id":"040","_name":"Cao Bằng","_prefix":"Thành phố","_province_id":"04"}, 
{"_id":"042","_name":"Bảo Lâm","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"043","_name":"Bảo Lạc","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"045","_name":"Hà Quảng","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"047","_name":"Trùng Khánh","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"048","_name":"Hạ Lang","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"049","_name":"Quảng Hòa","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"051","_name":"Hoà An","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"052","_name":"Nguyên Bình","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"053","_name":"Thạch An","_prefix":"Huyện","_province_id":"04"}, 
{"_id":"058","_name":"Bắc Kạn","_prefix":"Thành phố","_province_id":"06"}, 
{"_id":"060","_name":"Pác Nặm","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"061","_name":"Ba Bể","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"062","_name":"Ngân Sơn","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"063","_name":"Bạch Thông","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"064","_name":"Chợ Đồn","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"065","_name":"Chợ Mới","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"066","_name":"Na Rì","_prefix":"Huyện","_province_id":"06"}, 
{"_id":"070","_name":"Tuyên Quang","_prefix":"Thành phố","_province_id":"08"}, 
{"_id":"071","_name":"Lâm Bình","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"072","_name":"Na Hang","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"073","_name":"Chiêm Hóa","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"074","_name":"Hàm Yên","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"075","_name":"Yên Sơn","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"076","_name":"Sơn Dương","_prefix":"Huyện","_province_id":"08"}, 
{"_id":"080","_name":"Lào Cai","_prefix":"Thành phố","_province_id":"10"}, 
{"_id":"082","_name":"Bát Xát","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"083","_name":"Mường Khương","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"084","_name":"Si Ma Cai","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"085","_name":"Bắc Hà","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"086","_name":"Bảo Thắng","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"087","_name":"Bảo Yên","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"088","_name":"Thị Sa Pa","_prefix":"Thị xã","_province_id":"10"}, 
{"_id":"089","_name":"Văn Bàn","_prefix":"Huyện","_province_id":"10"}, 
{"_id":"094","_name":"Điện Biên Phủ","_prefix":"Thành phố","_province_id":"11"}, 
{"_id":"095","_name":"Thị Mường Lay","_prefix":"Thị xã","_province_id":"11"}, 
{"_id":"096","_name":"Mường Nhé","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"097","_name":"Mường Chà","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"098","_name":"Tủa Chùa","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"099","_name":"Tuần Giáo","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"100","_name":"Điện Biên","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"101","_name":"Điện Biên Đông","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"102","_name":"Mường Ảng","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"103","_name":"Nậm Pồ","_prefix":"Huyện","_province_id":"11"}, 
{"_id":"105","_name":"Lai Châu","_prefix":"Thành phố","_province_id":"12"}, 
{"_id":"106","_name":"Tam Đường","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"107","_name":"Mường Tè","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"108","_name":"Sìn Hồ","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"109","_name":"Phong Thổ","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"110","_name":"Than Uyên","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"111","_name":"Tân Uyên","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"112","_name":"Nậm Nhùn","_prefix":"Huyện","_province_id":"12"}, 
{"_id":"116","_name":"Sơn La","_prefix":"Thành phố","_province_id":"14"}, 
{"_id":"118","_name":"Quỳnh Nhai","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"119","_name":"Thuận Châu","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"120","_name":"Mường La","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"121","_name":"Bắc Yên","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"122","_name":"Phù Yên","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"123","_name":"Mộc Châu","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"124","_name":"Yên Châu","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"125","_name":"Mai Sơn","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"126","_name":"Sông Mã","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"127","_name":"Sốp Cộp","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"128","_name":"Vân Hồ","_prefix":"Huyện","_province_id":"14"}, 
{"_id":"132","_name":"Yên Bái","_prefix":"Thành phố","_province_id":"15"}, 
{"_id":"133","_name":"Thị Nghĩa Lộ","_prefix":"Thị xã","_province_id":"15"}, 
{"_id":"135","_name":"Lục Yên","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"136","_name":"Văn Yên","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"137","_name":"Mù Căng Chải","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"138","_name":"Trấn Yên","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"139","_name":"Trạm Tấu","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"140","_name":"Văn Chấn","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"141","_name":"Yên Bình","_prefix":"Huyện","_province_id":"15"}, 
{"_id":"148","_name":"Hòa Bình","_prefix":"Thành phố","_province_id":"17"}, 
{"_id":"150","_name":"Đà Bắc","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"152","_name":"Lương Sơn","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"153","_name":"Kim Bôi","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"154","_name":"Cao Phong","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"155","_name":"Tân Lạc","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"156","_name":"Mai Châu","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"157","_name":"Lạc Sơn","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"158","_name":"Yên Thủy","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"159","_name":"Lạc Thủy","_prefix":"Huyện","_province_id":"17"}, 
{"_id":"164","_name":"Thái Nguyên","_prefix":"Thành phố","_province_id":"19"}, 
{"_id":"165","_name":"Sông Công","_prefix":"Thành phố","_province_id":"19"}, 
{"_id":"167","_name":"Định Hóa","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"168","_name":"Phú Lương","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"169","_name":"Đồng Hỷ","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"170","_name":"Võ Nhai","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"171","_name":"Đại Từ","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"172","_name":"Thị Phổ Yên","_prefix":"Thị xã","_province_id":"19"}, 
{"_id":"173","_name":"Phú Bình","_prefix":"Huyện","_province_id":"19"}, 
{"_id":"178","_name":"Lạng Sơn","_prefix":"Thành phố","_province_id":"20"}, 
{"_id":"180","_name":"Tràng Định","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"181","_name":"Bình Gia","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"182","_name":"Văn Lãng","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"183","_name":"Cao Lộc","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"184","_name":"Văn Quan","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"185","_name":"Bắc Sơn","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"186","_name":"Hữu Lũng","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"187","_name":"Chi Lăng","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"188","_name":"Lộc Bình","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"189","_name":"Đình Lập","_prefix":"Huyện","_province_id":"20"}, 
{"_id":"193","_name":"Hạ Long","_prefix":"Thành phố","_province_id":"22"}, 
{"_id":"194","_name":"Móng Cái","_prefix":"Thành phố","_province_id":"22"}, 
{"_id":"195","_name":"Cẩm Phả","_prefix":"Thành phố","_province_id":"22"}, 
{"_id":"196","_name":"Uông Bí","_prefix":"Thành phố","_province_id":"22"}, 
{"_id":"198","_name":"Bình Liêu","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"199","_name":"Tiên Yên","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"200","_name":"Đầm Hà","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"201","_name":"Hải Hà","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"202","_name":"Ba Chẽ","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"203","_name":"Vân Đồn","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"205","_name":"Thị Đông Triều","_prefix":"Thị xã","_province_id":"22"}, 
{"_id":"206","_name":"Thị Quảng Yên","_prefix":"Thị xã","_province_id":"22"}, 
{"_id":"207","_name":"Cô Tô","_prefix":"Huyện","_province_id":"22"}, 
{"_id":"213","_name":"Bắc Giang","_prefix":"Thành phố","_province_id":"24"}, 
{"_id":"215","_name":"Yên Thế","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"216","_name":"Tân Yên","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"217","_name":"Lạng Giang","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"218","_name":"Lục Nam","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"219","_name":"Lục Ngạn","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"220","_name":"Sơn Động","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"221","_name":"Yên Dũng","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"222","_name":"Việt Yên","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"223","_name":"Hiệp Hòa","_prefix":"Huyện","_province_id":"24"}, 
{"_id":"227","_name":"Việt Trì","_prefix":"Thành phố","_province_id":"25"}, 
{"_id":"228","_name":"Thị Phú Thọ","_prefix":"Thị xã","_province_id":"25"}, 
{"_id":"230","_name":"Đoan Hùng","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"231","_name":"Hạ Hoà","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"232","_name":"Thanh Ba","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"233","_name":"Phù Ninh","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"234","_name":"Yên Lập","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"235","_name":"Cẩm Khê","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"236","_name":"Tam Nông","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"237","_name":"Lâm Thao","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"238","_name":"Thanh Sơn","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"239","_name":"Thanh Thuỷ","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"240","_name":"Tân Sơn","_prefix":"Huyện","_province_id":"25"}, 
{"_id":"243","_name":"Vĩnh Yên","_prefix":"Thành phố","_province_id":"26"}, 
{"_id":"244","_name":"Phúc Yên","_prefix":"Thành phố","_province_id":"26"}, 
{"_id":"246","_name":"Lập Thạch","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"247","_name":"Tam Dương","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"248","_name":"Tam Đảo","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"249","_name":"Bình Xuyên","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"250","_name":"Mê Linh","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"251","_name":"Yên Lạc","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"252","_name":"Vĩnh Tường","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"253","_name":"Sông Lô","_prefix":"Huyện","_province_id":"26"}, 
{"_id":"256","_name":"Bắc Ninh","_prefix":"Thành phố","_province_id":"27"}, 
{"_id":"258","_name":"Yên Phong","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"259","_name":"Quế Võ","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"260","_name":"Tiên Du","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"261","_name":"Thị Từ Sơn","_prefix":"Thị xã","_province_id":"27"}, 
{"_id":"262","_name":"Thuận Thành","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"263","_name":"Gia Bình","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"264","_name":"Lương Tài","_prefix":"Huyện","_province_id":"27"}, 
{"_id":"268","_name":"Hà Đông","_prefix":"Quận","_province_id":"01"}, 
{"_id":"269","_name":"Thị Sơn Tây","_prefix":"Thị xã","_province_id":"01"}, 
{"_id":"271","_name":"Ba Vì","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"272","_name":"Phúc Thọ","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"273","_name":"Đan Phượng","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"274","_name":"Hoài Đức","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"275","_name":"Quốc Oai","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"276","_name":"Thạch Thất","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"277","_name":"Chương Mỹ","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"278","_name":"Thanh Oai","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"279","_name":"Thường Tín","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"280","_name":"Phú Xuyên","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"281","_name":"Ứng Hòa","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"282","_name":"Mỹ Đức","_prefix":"Huyện","_province_id":"01"}, 
{"_id":"288","_name":"Hải Dương","_prefix":"Thành phố","_province_id":"30"}, 
{"_id":"290","_name":"Chí Linh","_prefix":"Thành phố","_province_id":"30"}, 
{"_id":"291","_name":"Nam Sách","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"292","_name":"Thị Kinh Môn","_prefix":"Thị xã","_province_id":"30"}, 
{"_id":"293","_name":"Kim Thành","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"294","_name":"Thanh Hà","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"295","_name":"Cẩm Giàng","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"296","_name":"Bình Giang","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"297","_name":"Gia Lộc","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"298","_name":"Tứ Kỳ","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"299","_name":"Ninh Giang","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"300","_name":"Thanh Miện","_prefix":"Huyện","_province_id":"30"}, 
{"_id":"303","_name":"Hồng Bàng","_prefix":"Quận","_province_id":"31"}, 
{"_id":"304","_name":"Ngô Quyền","_prefix":"Quận","_province_id":"31"}, 
{"_id":"305","_name":"Lê Chân","_prefix":"Quận","_province_id":"31"}, 
{"_id":"306","_name":"Hải An","_prefix":"Quận","_province_id":"31"}, 
{"_id":"307","_name":"Kiến An","_prefix":"Quận","_province_id":"31"}, 
{"_id":"308","_name":"Đồ Sơn","_prefix":"Quận","_province_id":"31"}, 
{"_id":"309","_name":"Dương Kinh","_prefix":"Quận","_province_id":"31"}, 
{"_id":"311","_name":"Thuỷ Nguyên","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"312","_name":"An Dương","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"313","_name":"An Lão","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"314","_name":"Kiến Thuỵ","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"315","_name":"Tiên Lãng","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"316","_name":"Vĩnh Bảo","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"317","_name":"Cát Hải","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"318","_name":"Bạch Long Vĩ","_prefix":"Huyện","_province_id":"31"}, 
{"_id":"323","_name":"Hưng Yên","_prefix":"Thành phố","_province_id":"33"}, 
{"_id":"325","_name":"Văn Lâm","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"326","_name":"Văn Giang","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"327","_name":"Yên Mỹ","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"328","_name":"Thị Mỹ Hào","_prefix":"Thị xã","_province_id":"33"}, 
{"_id":"329","_name":"Ân Thi","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"330","_name":"Khoái Châu","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"331","_name":"Kim Động","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"332","_name":"Tiên Lữ","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"333","_name":"Phù Cừ","_prefix":"Huyện","_province_id":"33"}, 
{"_id":"336","_name":"Thái Bình","_prefix":"Thành phố","_province_id":"34"}, 
{"_id":"338","_name":"Quỳnh Phụ","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"339","_name":"Hưng Hà","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"340","_name":"Đông Hưng","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"341","_name":"Thái Thụy","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"342","_name":"Tiền Hải","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"343","_name":"Kiến Xương","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"344","_name":"Vũ Thư","_prefix":"Huyện","_province_id":"34"}, 
{"_id":"347","_name":"Phủ Lý","_prefix":"Thành phố","_province_id":"35"}, 
{"_id":"349","_name":"Thị Duy Tiên","_prefix":"Thị xã","_province_id":"35"}, 
{"_id":"350","_name":"Kim Bảng","_prefix":"Huyện","_province_id":"35"}, 
{"_id":"351","_name":"Thanh Liêm","_prefix":"Huyện","_province_id":"35"}, 
{"_id":"352","_name":"Bình Lục","_prefix":"Huyện","_province_id":"35"}, 
{"_id":"353","_name":"Lý Nhân","_prefix":"Huyện","_province_id":"35"}, 
{"_id":"356","_name":"Nam Định","_prefix":"Thành phố","_province_id":"36"}, 
{"_id":"358","_name":"Mỹ Lộc","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"359","_name":"Vụ Bản","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"360","_name":"Ý Yên","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"361","_name":"Nghĩa Hưng","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"362","_name":"Nam Trực","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"363","_name":"Trực Ninh","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"364","_name":"Xuân Trường","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"365","_name":"Giao Thủy","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"366","_name":"Hải Hậu","_prefix":"Huyện","_province_id":"36"}, 
{"_id":"369","_name":"Ninh Bình","_prefix":"Thành phố","_province_id":"37"}, 
{"_id":"370","_name":"Tam Điệp","_prefix":"Thành phố","_province_id":"37"}, 
{"_id":"372","_name":"Nho Quan","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"373","_name":"Gia Viễn","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"374","_name":"Hoa Lư","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"375","_name":"Yên Khánh","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"376","_name":"Kim Sơn","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"377","_name":"Yên Mô","_prefix":"Huyện","_province_id":"37"}, 
{"_id":"380","_name":"Thanh Hóa","_prefix":"Thành phố","_province_id":"38"}, 
{"_id":"381","_name":"Thị Bỉm Sơn","_prefix":"Thị xã","_province_id":"38"}, 
{"_id":"382","_name":"Sầm Sơn","_prefix":"Thành phố","_province_id":"38"}, 
{"_id":"384","_name":"Mường Lát","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"385","_name":"Quan Hóa","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"386","_name":"Bá Thước","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"387","_name":"Quan Sơn","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"388","_name":"Lang Chánh","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"389","_name":"Ngọc Lặc","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"390","_name":"Cẩm Thủy","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"391","_name":"Thạch Thành","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"392","_name":"Hà Trung","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"393","_name":"Vĩnh Lộc","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"394","_name":"Yên Định","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"395","_name":"Thọ Xuân","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"396","_name":"Thường Xuân","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"397","_name":"Triệu Sơn","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"398","_name":"Thiệu Hóa","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"399","_name":"Hoằng Hóa","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"400","_name":"Hậu Lộc","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"401","_name":"Nga Sơn","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"402","_name":"Như Xuân","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"403","_name":"Như Thanh","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"404","_name":"Nông Cống","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"405","_name":"Đông Sơn","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"406","_name":"Quảng Xương","_prefix":"Huyện","_province_id":"38"}, 
{"_id":"407","_name":"Thị Nghi Sơn","_prefix":"Thị xã","_province_id":"38"}, 
{"_id":"412","_name":"Vinh","_prefix":"Thành phố","_province_id":"40"}, 
{"_id":"413","_name":"Thị Cửa Lò","_prefix":"Thị xã","_province_id":"40"}, 
{"_id":"414","_name":"Thị Thái Hoà","_prefix":"Thị xã","_province_id":"40"}, 
{"_id":"415","_name":"Quế Phong","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"416","_name":"Quỳ Châu","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"417","_name":"Kỳ Sơn","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"418","_name":"Tương Dương","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"419","_name":"Nghĩa Đàn","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"420","_name":"Quỳ Hợp","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"421","_name":"Quỳnh Lưu","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"422","_name":"Con Cuông","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"423","_name":"Tân Kỳ","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"424","_name":"Anh Sơn","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"425","_name":"Diễn Châu","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"426","_name":"Yên Thành","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"427","_name":"Đô Lương","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"428","_name":"Thanh Chương","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"429","_name":"Nghi Lộc","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"430","_name":"Nam Đàn","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"431","_name":"Hưng Nguyên","_prefix":"Huyện","_province_id":"40"}, 
{"_id":"432","_name":"Thị Hoàng Mai","_prefix":"Thị xã","_province_id":"40"}, 
{"_id":"436","_name":"Hà Tĩnh","_prefix":"Thành phố","_province_id":"42"}, 
{"_id":"437","_name":"Thị Hồng Lĩnh","_prefix":"Thị xã","_province_id":"42"}, 
{"_id":"439","_name":"Hương Sơn","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"440","_name":"Đức Thọ","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"441","_name":"Vũ Quang","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"442","_name":"Nghi Xuân","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"443","_name":"Can Lộc","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"444","_name":"Hương Khê","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"445","_name":"Thạch Hà","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"446","_name":"Cẩm Xuyên","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"447","_name":"Kỳ Anh","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"448","_name":"Lộc Hà","_prefix":"Huyện","_province_id":"42"}, 
{"_id":"449","_name":"Thị Kỳ Anh","_prefix":"Thị xã","_province_id":"42"}, 
{"_id":"450","_name":"Đồng Hới","_prefix":"Thành phố","_province_id":"44"}, 
{"_id":"452","_name":"Minh Hóa","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"453","_name":"Tuyên Hóa","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"454","_name":"Quảng Trạch","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"455","_name":"Bố Trạch","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"456","_name":"Quảng Ninh","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"457","_name":"Lệ Thủy","_prefix":"Huyện","_province_id":"44"}, 
{"_id":"458","_name":"Thị Ba Đồn","_prefix":"Thị xã","_province_id":"44"}, 
{"_id":"461","_name":"Đông Hà","_prefix":"Thành phố","_province_id":"45"}, 
{"_id":"462","_name":"Thị Quảng Trị","_prefix":"Thị xã","_province_id":"45"}, 
{"_id":"464","_name":"Vĩnh Linh","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"465","_name":"Hướng Hóa","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"466","_name":"Gio Linh","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"467","_name":"Đa Krông","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"468","_name":"Cam Lộ","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"469","_name":"Triệu Phong","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"470","_name":"Hải Lăng","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"471","_name":"Cồn Cỏ","_prefix":"Huyện","_province_id":"45"}, 
{"_id":"474","_name":"Huế","_prefix":"Thành phố","_province_id":"46"}, 
{"_id":"476","_name":"Phong Điền","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"477","_name":"Quảng Điền","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"478","_name":"Phú Vang","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"479","_name":"Thị Hương Thủy","_prefix":"Thị xã","_province_id":"46"}, 
{"_id":"480","_name":"Thị Hương Trà","_prefix":"Thị xã","_province_id":"46"}, 
{"_id":"481","_name":"A Lưới","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"482","_name":"Phú Lộc","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"483","_name":"Nam Đông","_prefix":"Huyện","_province_id":"46"}, 
{"_id":"490","_name":"Liên Chiểu","_prefix":"Quận","_province_id":"48"}, 
{"_id":"491","_name":"Thanh Khê","_prefix":"Quận","_province_id":"48"}, 
{"_id":"492","_name":"Hải Châu","_prefix":"Quận","_province_id":"48"}, 
{"_id":"493","_name":"Sơn Trà","_prefix":"Quận","_province_id":"48"}, 
{"_id":"494","_name":"Ngũ Hành Sơn","_prefix":"Quận","_province_id":"48"}, 
{"_id":"495","_name":"Cẩm Lệ","_prefix":"Quận","_province_id":"48"}, 
{"_id":"497","_name":"Hòa Vang","_prefix":"Huyện","_province_id":"48"}, 
{"_id":"498","_name":"Hoàng Sa","_prefix":"Huyện","_province_id":"48"}, 
{"_id":"502","_name":"Tam Kỳ","_prefix":"Thành phố","_province_id":"49"}, 
{"_id":"503","_name":"Hội An","_prefix":"Thành phố","_province_id":"49"}, 
{"_id":"504","_name":"Tây Giang","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"505","_name":"Đông Giang","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"506","_name":"Đại Lộc","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"507","_name":"Thị Điện Bàn","_prefix":"Thị xã","_province_id":"49"}, 
{"_id":"508","_name":"Duy Xuyên","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"509","_name":"Quế Sơn","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"510","_name":"Nam Giang","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"511","_name":"Phước Sơn","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"512","_name":"Hiệp Đức","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"513","_name":"Thăng Bình","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"514","_name":"Tiên Phước","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"515","_name":"Bắc Trà My","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"516","_name":"Nam Trà My","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"517","_name":"Núi Thành","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"518","_name":"Phú Ninh","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"519","_name":"Nông Sơn","_prefix":"Huyện","_province_id":"49"}, 
{"_id":"522","_name":"Quảng Ngãi","_prefix":"Thành phố","_province_id":"51"}, 
{"_id":"524","_name":"Bình Sơn","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"525","_name":"Trà Bồng","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"527","_name":"Sơn Tịnh","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"528","_name":"Tư Nghĩa","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"529","_name":"Sơn Hà","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"530","_name":"Sơn Tây","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"531","_name":"Minh Long","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"532","_name":"Nghĩa Hành","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"533","_name":"Mộ Đức","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"534","_name":"Thị Đức Phổ","_prefix":"Thị xã","_province_id":"51"}, 
{"_id":"535","_name":"Ba Tơ","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"536","_name":"Lý Sơn","_prefix":"Huyện","_province_id":"51"}, 
{"_id":"540","_name":"Qui Nhơn","_prefix":"Thành phố","_province_id":"52"}, 
{"_id":"542","_name":"An Lão","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"543","_name":"Thị Hoài Nhơn","_prefix":"Thị xã","_province_id":"52"}, 
{"_id":"544","_name":"Hoài Ân","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"545","_name":"Phù Mỹ","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"546","_name":"Vĩnh Thạnh","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"547","_name":"Tây Sơn","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"548","_name":"Phù Cát","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"549","_name":"Thị An Nhơn","_prefix":"Thị xã","_province_id":"52"}, 
{"_id":"550","_name":"Tuy Phước","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"551","_name":"Vân Canh","_prefix":"Huyện","_province_id":"52"}, 
{"_id":"555","_name":"Tuy Hoà","_prefix":"Thành phố","_province_id":"54"}, 
{"_id":"557","_name":"Thị Sông Cầu","_prefix":"Thị xã","_province_id":"54"}, 
{"_id":"558","_name":"Đồng Xuân","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"559","_name":"Tuy An","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"560","_name":"Sơn Hòa","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"561","_name":"Sông Hinh","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"562","_name":"Tây Hoà","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"563","_name":"Phú Hoà","_prefix":"Huyện","_province_id":"54"}, 
{"_id":"564","_name":"Thị Đông Hòa","_prefix":"Thị xã","_province_id":"54"}, 
{"_id":"568","_name":"Nha Trang","_prefix":"Thành phố","_province_id":"56"}, 
{"_id":"569","_name":"Cam Ranh","_prefix":"Thành phố","_province_id":"56"}, 
{"_id":"570","_name":"Cam Lâm","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"571","_name":"Vạn Ninh","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"572","_name":"Thị Ninh Hòa","_prefix":"Thị xã","_province_id":"56"}, 
{"_id":"573","_name":"Khánh Vĩnh","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"574","_name":"Diên Khánh","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"575","_name":"Khánh Sơn","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"576","_name":"Trường Sa","_prefix":"Huyện","_province_id":"56"}, 
{"_id":"582","_name":"Phan Rang-Tháp Chàm","_prefix":"Thành phố","_province_id":"58"}, 
{"_id":"584","_name":"Bác Ái","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"585","_name":"Ninh Sơn","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"586","_name":"Ninh Hải","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"587","_name":"Ninh Phước","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"588","_name":"Thuận Bắc","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"589","_name":"Thuận Nam","_prefix":"Huyện","_province_id":"58"}, 
{"_id":"593","_name":"Phan Thiết","_prefix":"Thành phố","_province_id":"60"}, 
{"_id":"594","_name":"Thị La Gi","_prefix":"Thị xã","_province_id":"60"}, 
{"_id":"595","_name":"Tuy Phong","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"596","_name":"Bắc Bình","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"597","_name":"Hàm Thuận Bắc","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"598","_name":"Hàm Thuận Nam","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"599","_name":"Tánh Linh","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"600","_name":"Đức Linh","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"601","_name":"Hàm Tân","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"602","_name":"Phú Quí","_prefix":"Huyện","_province_id":"60"}, 
{"_id":"608","_name":"Kon Tum","_prefix":"Thành phố","_province_id":"62"}, 
{"_id":"610","_name":"Đắk Glei","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"611","_name":"Ngọc Hồi","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"612","_name":"Đắk Tô","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"613","_name":"Kon Plông","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"614","_name":"Kon Rẫy","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"615","_name":"Đắk Hà","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"616","_name":"Sa Thầy","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"617","_name":"Tu Mơ Rông","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"618","_name":"Ia H_Drai","_prefix":"Huyện","_province_id":"62"}, 
{"_id":"622","_name":"Pleiku","_prefix":"Thành phố","_province_id":"64"}, 
{"_id":"623","_name":"Thị An Khê","_prefix":"Thị xã","_province_id":"64"}, 
{"_id":"624","_name":"Thị Ayun Pa","_prefix":"Thị xã","_province_id":"64"}, 
{"_id":"625","_name":"KBang","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"626","_name":"Đăk Đoa","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"627","_name":"Chư Păh","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"628","_name":"Ia Grai","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"629","_name":"Mang Yang","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"630","_name":"Kông Chro","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"631","_name":"Đức Cơ","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"632","_name":"Chư Prông","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"633","_name":"Chư Sê","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"634","_name":"Đăk Pơ","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"635","_name":"Ia Pa","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"637","_name":"Krông Pa","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"638","_name":"Phú Thiện","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"639","_name":"Chư Pưh","_prefix":"Huyện","_province_id":"64"}, 
{"_id":"643","_name":"Buôn Ma Thuột","_prefix":"Thành phố","_province_id":"66"}, 
{"_id":"644","_name":"Thị Buôn Hồ","_prefix":"Thị xã","_province_id":"66"}, 
{"_id":"645","_name":"Ea Hleo","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"646","_name":"Ea Súp","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"647","_name":"Buôn Đôn","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"648","_name":"Cư M_gar","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"649","_name":"Krông Búk","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"650","_name":"Krông Năng","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"651","_name":"Ea Kar","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"652","_name":"MĐrắk","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"653","_name":"Krông Bông","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"654","_name":"Krông Pắc","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"655","_name":"Krông A Na","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"656","_name":"Lắk","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"657","_name":"Cư Kuin","_prefix":"Huyện","_province_id":"66"}, 
{"_id":"660","_name":"Gia Nghĩa","_prefix":"Thành phố","_province_id":"67"}, 
{"_id":"661","_name":"Đăk Glong","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"662","_name":"Cư Jút","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"663","_name":"Đắk Mil","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"664","_name":"Krông Nô","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"665","_name":"Đắk Song","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"666","_name":"Đắk RLấp","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"667","_name":"Tuy Đức","_prefix":"Huyện","_province_id":"67"}, 
{"_id":"672","_name":"Đà Lạt","_prefix":"Thành phố","_province_id":"68"}, 
{"_id":"673","_name":"Bảo Lộc","_prefix":"Thành phố","_province_id":"68"}, 
{"_id":"674","_name":"Đam Rông","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"675","_name":"Lạc Dương","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"676","_name":"Lâm Hà","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"677","_name":"Đơn Dương","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"678","_name":"Đức Trọng","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"679","_name":"Di Linh","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"680","_name":"Bảo Lâm","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"681","_name":"Đạ Huoai","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"682","_name":"Đạ Tẻh","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"683","_name":"Cát Tiên","_prefix":"Huyện","_province_id":"68"}, 
{"_id":"688","_name":"Thị Phước Long","_prefix":"Thị xã","_province_id":"70"}, 
{"_id":"689","_name":"Đồng Xoài","_prefix":"Thành phố","_province_id":"70"}, 
{"_id":"690","_name":"Thị Bình Long","_prefix":"Thị xã","_province_id":"70"}, 
{"_id":"691","_name":"Bù Gia Mập","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"692","_name":"Lộc Ninh","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"693","_name":"Bù Đốp","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"694","_name":"Hớn Quản","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"695","_name":"Đồng Phú","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"696","_name":"Bù Đăng","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"697","_name":"Chơn Thành","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"698","_name":"Phú Riềng","_prefix":"Huyện","_province_id":"70"}, 
{"_id":"703","_name":"Tây Ninh","_prefix":"Thành phố","_province_id":"72"}, 
{"_id":"705","_name":"Tân Biên","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"706","_name":"Tân Châu","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"707","_name":"Dương Minh Châu","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"708","_name":"Châu Thành","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"709","_name":"Thị Hòa Thành","_prefix":"Thị xã","_province_id":"72"}, 
{"_id":"710","_name":"Gò Dầu","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"711","_name":"Bến Cầu","_prefix":"Huyện","_province_id":"72"}, 
{"_id":"712","_name":"Thị Trảng Bàng","_prefix":"Thị xã","_province_id":"72"}, 
{"_id":"718","_name":"Thủ Dầu Một","_prefix":"Thành phố","_province_id":"74"}, 
{"_id":"719","_name":"Bàu Bàng","_prefix":"Huyện","_province_id":"74"}, 
{"_id":"720","_name":"Dầu Tiếng","_prefix":"Huyện","_province_id":"74"}, 
{"_id":"721","_name":"Thị Bến Cát","_prefix":"Thị xã","_province_id":"74"}, 
{"_id":"722","_name":"Phú Giáo","_prefix":"Huyện","_province_id":"74"}, 
{"_id":"723","_name":"Thị Tân Uyên","_prefix":"Thị xã","_province_id":"74"}, 
{"_id":"724","_name":"Dĩ An","_prefix":"Thành phố","_province_id":"74"}, 
{"_id":"725","_name":"Thuận An","_prefix":"Thành phố","_province_id":"74"}, 
{"_id":"726","_name":"Bắc Tân Uyên","_prefix":"Huyện","_province_id":"74"}, 
{"_id":"731","_name":"Biên Hòa","_prefix":"Thành phố","_province_id":"75"}, 
{"_id":"732","_name":"Long Khánh","_prefix":"Thành phố","_province_id":"75"}, 
{"_id":"734","_name":"Tân Phú","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"735","_name":"Vĩnh Cửu","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"736","_name":"Định Quán","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"737","_name":"Trảng Bom","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"738","_name":"Thống Nhất","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"739","_name":"Cẩm Mỹ","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"740","_name":"Long Thành","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"741","_name":"Xuân Lộc","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"742","_name":"Nhơn Trạch","_prefix":"Huyện","_province_id":"75"}, 
{"_id":"747","_name":"Vũng Tàu","_prefix":"Thành phố","_province_id":"77"}, 
{"_id":"748","_name":"Bà Rịa","_prefix":"Thành phố","_province_id":"77"}, 
{"_id":"750","_name":"Châu Đức","_prefix":"Huyện","_province_id":"77"}, 
{"_id":"751","_name":"Xuyên Mộc","_prefix":"Huyện","_province_id":"77"}, 
{"_id":"752","_name":"Long Điền","_prefix":"Huyện","_province_id":"77"}, 
{"_id":"753","_name":"Đất Đỏ","_prefix":"Huyện","_province_id":"77"}, 
{"_id":"754","_name":"Thị Phú Mỹ","_prefix":"Thị xã","_province_id":"77"}, 
{"_id":"755","_name":"Côn Đảo","_prefix":"Huyện","_province_id":"77"}, 
{"_id":"760","_name":"1","_prefix":"Quận","_province_id":"79"}, 
{"_id":"761","_name":"12","_prefix":"Quận","_province_id":"79"}, 
{"_id":"762","_name":"Thủ Đức","_prefix":"Quận","_province_id":"79"}, 
{"_id":"763","_name":"9","_prefix":"Quận","_province_id":"79"}, 
{"_id":"764","_name":"Gò Vấp","_prefix":"Quận","_province_id":"79"}, 
{"_id":"765","_name":"Bình Thạnh","_prefix":"Quận","_province_id":"79"}, 
{"_id":"766","_name":"Tân Bình","_prefix":"Quận","_province_id":"79"}, 
{"_id":"767","_name":"Tân Phú","_prefix":"Quận","_province_id":"79"}, 
{"_id":"768","_name":"Phú Nhuận","_prefix":"Quận","_province_id":"79"}, 
{"_id":"769","_name":"2","_prefix":"Quận","_province_id":"79"}, 
{"_id":"770","_name":"3","_prefix":"Quận","_province_id":"79"}, 
{"_id":"771","_name":"10","_prefix":"Quận","_province_id":"79"}, 
{"_id":"772","_name":"11","_prefix":"Quận","_province_id":"79"}, 
{"_id":"773","_name":"4","_prefix":"Quận","_province_id":"79"}, 
{"_id":"774","_name":"5","_prefix":"Quận","_province_id":"79"}, 
{"_id":"775","_name":"6","_prefix":"Quận","_province_id":"79"}, 
{"_id":"776","_name":"8","_prefix":"Quận","_province_id":"79"}, 
{"_id":"777","_name":"Bình Tân","_prefix":"Quận","_province_id":"79"}, 
{"_id":"778","_name":"7","_prefix":"Quận","_province_id":"79"}, 
{"_id":"783","_name":"Củ Chi","_prefix":"Huyện","_province_id":"79"}, 
{"_id":"784","_name":"Hóc Môn","_prefix":"Huyện","_province_id":"79"}, 
{"_id":"785","_name":"Bình Chánh","_prefix":"Huyện","_province_id":"79"}, 
{"_id":"786","_name":"Nhà Bè","_prefix":"Huyện","_province_id":"79"}, 
{"_id":"787","_name":"Cần Giờ","_prefix":"Huyện","_province_id":"79"}, 
{"_id":"794","_name":"Tân An","_prefix":"Thành phố","_province_id":"80"}, 
{"_id":"795","_name":"Thị Kiến Tường","_prefix":"Thị xã","_province_id":"80"}, 
{"_id":"796","_name":"Tân Hưng","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"797","_name":"Vĩnh Hưng","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"798","_name":"Mộc Hóa","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"799","_name":"Tân Thạnh","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"800","_name":"Thạnh Hóa","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"801","_name":"Đức Huệ","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"802","_name":"Đức Hòa","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"803","_name":"Bến Lức","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"804","_name":"Thủ Thừa","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"805","_name":"Tân Trụ","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"806","_name":"Cần Đước","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"807","_name":"Cần Giuộc","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"808","_name":"Châu Thành","_prefix":"Huyện","_province_id":"80"}, 
{"_id":"815","_name":"Mỹ Tho","_prefix":"Thành phố","_province_id":"82"}, 
{"_id":"816","_name":"Thị Gò Công","_prefix":"Thị xã","_province_id":"82"}, 
{"_id":"817","_name":"Thị Cai Lậy","_prefix":"Thị xã","_province_id":"82"}, 
{"_id":"818","_name":"Tân Phước","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"819","_name":"Cái Bè","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"820","_name":"Cai Lậy","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"821","_name":"Châu Thành","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"822","_name":"Chợ Gạo","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"823","_name":"Gò Công Tây","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"824","_name":"Gò Công Đông","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"825","_name":"Tân Phú Đông","_prefix":"Huyện","_province_id":"82"}, 
{"_id":"829","_name":"Bến Tre","_prefix":"Thành phố","_province_id":"83"}, 
{"_id":"831","_name":"Châu Thành","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"832","_name":"Chợ Lách","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"833","_name":"Mỏ Cày Nam","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"834","_name":"Giồng Trôm","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"835","_name":"Bình Đại","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"836","_name":"Ba Tri","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"837","_name":"Thạnh Phú","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"838","_name":"Mỏ Cày Bắc","_prefix":"Huyện","_province_id":"83"}, 
{"_id":"842","_name":"Trà Vinh","_prefix":"Thành phố","_province_id":"84"}, 
{"_id":"844","_name":"Càng Long","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"845","_name":"Cầu Kè","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"846","_name":"Tiểu Cần","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"847","_name":"Châu Thành","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"848","_name":"Cầu Ngang","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"849","_name":"Trà Cú","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"850","_name":"Duyên Hải","_prefix":"Huyện","_province_id":"84"}, 
{"_id":"851","_name":"Thị Duyên Hải","_prefix":"Thị xã","_province_id":"84"}, 
{"_id":"855","_name":"Vĩnh Long","_prefix":"Thành phố","_province_id":"86"}, 
{"_id":"857","_name":"Long Hồ","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"858","_name":"Mang Thít","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"859","_name":" Vũng Liêm","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"860","_name":"Tam Bình","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"861","_name":"Thị Bình Minh","_prefix":"Thị xã","_province_id":"86"}, 
{"_id":"862","_name":"Trà Ôn","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"863","_name":"Bình Tân","_prefix":"Huyện","_province_id":"86"}, 
{"_id":"866","_name":"Cao Lãnh","_prefix":"Thành phố","_province_id":"87"}, 
{"_id":"867","_name":"Sa Đéc","_prefix":"Thành phố","_province_id":"87"}, 
{"_id":"868","_name":"Thị Hồng Ngự","_prefix":"Thị xã","_province_id":"87"}, 
{"_id":"869","_name":"Tân Hồng","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"870","_name":"Hồng Ngự","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"871","_name":"Tam Nông","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"872","_name":"Tháp Mười","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"873","_name":"Cao Lãnh","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"874","_name":"Thanh Bình","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"875","_name":"Lấp Vò","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"876","_name":"Lai Vung","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"877","_name":"Châu Thành","_prefix":"Huyện","_province_id":"87"}, 
{"_id":"883","_name":"Long Xuyên","_prefix":"Thành phố","_province_id":"89"}, 
{"_id":"884","_name":"Châu Đốc","_prefix":"Thành phố","_province_id":"89"}, 
{"_id":"886","_name":"An Phú","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"887","_name":"Thị Tân Châu","_prefix":"Thị xã","_province_id":"89"}, 
{"_id":"888","_name":"Phú Tân","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"889","_name":"Châu Phú","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"890","_name":"Tịnh Biên","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"891","_name":"Tri Tôn","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"892","_name":"Châu Thành","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"893","_name":"Chợ Mới","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"894","_name":"Thoại Sơn","_prefix":"Huyện","_province_id":"89"}, 
{"_id":"899","_name":"Rạch Giá","_prefix":"Thành phố","_province_id":"91"}, 
{"_id":"900","_name":"Hà Tiên","_prefix":"Thành phố","_province_id":"91"}, 
{"_id":"902","_name":"Kiên Lương","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"903","_name":"Hòn Đất","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"904","_name":"Tân Hiệp","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"905","_name":"Châu Thành","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"906","_name":"Giồng Riềng","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"907","_name":"Gò Quao","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"908","_name":"An Biên","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"909","_name":"An Minh","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"910","_name":"Vĩnh Thuận","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"911","_name":"Phú Quốc","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"912","_name":"Kiên Hải","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"913","_name":"U Minh Thượng","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"914","_name":"Giang Thành","_prefix":"Huyện","_province_id":"91"}, 
{"_id":"916","_name":"Ninh Kiều","_prefix":"Quận","_province_id":"92"}, 
{"_id":"917","_name":"Ô Môn","_prefix":"Quận","_province_id":"92"}, 
{"_id":"918","_name":"Bình Thuỷ","_prefix":"Quận","_province_id":"92"}, 
{"_id":"919","_name":"Cái Răng","_prefix":"Quận","_province_id":"92"}, 
{"_id":"923","_name":"Thốt Nốt","_prefix":"Quận","_province_id":"92"}, 
{"_id":"924","_name":"Vĩnh Thạnh","_prefix":"Huyện","_province_id":"92"}, 
{"_id":"925","_name":"Cờ Đỏ","_prefix":"Huyện","_province_id":"92"}, 
{"_id":"926","_name":"Phong Điền","_prefix":"Huyện","_province_id":"92"}, 
{"_id":"927","_name":"Thới Lai","_prefix":"Huyện","_province_id":"92"}, 
{"_id":"930","_name":"Vị Thanh","_prefix":"Thành phố","_province_id":"93"}, 
{"_id":"931","_name":"Ngã Bảy","_prefix":"Thành phố","_province_id":"93"}, 
{"_id":"932","_name":"Châu Thành A","_prefix":"Huyện","_province_id":"93"}, 
{"_id":"933","_name":"Châu Thành","_prefix":"Huyện","_province_id":"93"}, 
{"_id":"934","_name":"Phụng Hiệp","_prefix":"Huyện","_province_id":"93"}, 
{"_id":"935","_name":"Vị Thuỷ","_prefix":"Huyện","_province_id":"93"}, 
{"_id":"936","_name":"Long Mỹ","_prefix":"Huyện","_province_id":"93"}, 
{"_id":"937","_name":"Thị Long Mỹ","_prefix":"Thị xã","_province_id":"93"}, 
{"_id":"941","_name":"Sóc Trăng","_prefix":"Thành phố","_province_id":"94"}, 
{"_id":"942","_name":"Châu Thành","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"943","_name":"Kế Sách","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"944","_name":"Mỹ Tú","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"945","_name":"Cù Lao Dung","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"946","_name":"Long Phú","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"947","_name":"Mỹ Xuyên","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"948","_name":"Thị Ngã Năm","_prefix":"Thị xã","_province_id":"94"}, 
{"_id":"949","_name":"Thạnh Trị","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"950","_name":"Thị Vĩnh Châu","_prefix":"Thị xã","_province_id":"94"}, 
{"_id":"951","_name":"Trần Đề","_prefix":"Huyện","_province_id":"94"}, 
{"_id":"954","_name":"Bạc Liêu","_prefix":"Thành phố","_province_id":"95"}, 
{"_id":"956","_name":"Hồng Dân","_prefix":"Huyện","_province_id":"95"}, 
{"_id":"957","_name":"Phước Long","_prefix":"Huyện","_province_id":"95"}, 
{"_id":"958","_name":"Vĩnh Lợi","_prefix":"Huyện","_province_id":"95"}, 
{"_id":"959","_name":"Thị Giá Rai","_prefix":"Thị xã","_province_id":"95"}, 
{"_id":"960","_name":"Đông Hải","_prefix":"Huyện","_province_id":"95"}, 
{"_id":"961","_name":"Hoà Bình","_prefix":"Huyện","_province_id":"95"}, 
{"_id":"964","_name":"Cà Mau","_prefix":"Thành phố","_province_id":"96"}, 
{"_id":"966","_name":"U Minh","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"967","_name":"Thới Bình","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"968","_name":"Trần Văn Thời","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"969","_name":"Cái Nước","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"970","_name":"Đầm Dơi","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"971","_name":"Năm Căn","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"972","_name":"Phú Tân","_prefix":"Huyện","_province_id":"96"}, 
{"_id":"973","_name":"Ngọc Hiển","_prefix":"Huyện","_province_id":"96"}]

 export default initialDistrict