var initialProvince = [{"_id":"01","_name":"Hà Nội","_prefix":"Trung ương"}, 
{"_id":"02","_name":"Hà Giang","_prefix":"Tỉnh"}, 
{"_id":"04","_name":"Cao Bằng","_prefix":"Tỉnh"}, 
{"_id":"06","_name":"Bắc Kạn","_prefix":"Tỉnh"}, 
{"_id":"08","_name":"Tuyên Quang","_prefix":"Tỉnh"}, 
{"_id":"10","_name":"Lào Cai","_prefix":"Tỉnh"}, 
{"_id":"11","_name":"Điện Biên","_prefix":"Tỉnh"}, 
{"_id":"12","_name":"Lai Châu","_prefix":"Tỉnh"}, 
{"_id":"14","_name":"Sơn La","_prefix":"Tỉnh"}, 
{"_id":"15","_name":"Yên Bái","_prefix":"Tỉnh"}, 
{"_id":"17","_name":"Hoà Bình","_prefix":"Tỉnh"}, 
{"_id":"19","_name":"Thái Nguyên","_prefix":"Tỉnh"}, 
{"_id":"20","_name":"Lạng Sơn","_prefix":"Tỉnh"}, 
{"_id":"22","_name":"Quảng Ninh","_prefix":"Tỉnh"}, 
{"_id":"24","_name":"Bắc Giang","_prefix":"Tỉnh"}, 
{"_id":"25","_name":"Phú Thọ","_prefix":"Tỉnh"}, 
{"_id":"26","_name":"Vĩnh Phúc","_prefix":"Tỉnh"}, 
{"_id":"27","_name":"Bắc Ninh","_prefix":"Tỉnh"}, 
{"_id":"30","_name":"Hải Dương","_prefix":"Tỉnh"}, 
{"_id":"31","_name":"Hải Phòng","_prefix":"Trung ương"}, 
{"_id":"33","_name":"Hưng Yên","_prefix":"Tỉnh"}, 
{"_id":"34","_name":"Thái Bình","_prefix":"Tỉnh"}, 
{"_id":"35","_name":"Hà Nam","_prefix":"Tỉnh"}, 
{"_id":"36","_name":"Nam Định","_prefix":"Tỉnh"}, 
{"_id":"37","_name":"Ninh Bình","_prefix":"Tỉnh"}, 
{"_id":"38","_name":"Thanh Hóa","_prefix":"Tỉnh"}, 
{"_id":"40","_name":"Nghệ An","_prefix":"Tỉnh"}, 
{"_id":"42","_name":"Hà Tĩnh","_prefix":"Tỉnh"}, 
{"_id":"44","_name":"Quảng Bình","_prefix":"Tỉnh"}, 
{"_id":"45","_name":"Quảng Trị","_prefix":"Tỉnh"}, 
{"_id":"46","_name":"Thừa Thiên Huế","_prefix":"Tỉnh"}, 
{"_id":"48","_name":"Đà Nẵng","_prefix":"Trung ương"}, 
{"_id":"49","_name":"Quảng Nam","_prefix":"Tỉnh"}, 
{"_id":"51","_name":"Quảng Ngãi","_prefix":"Tỉnh"}, 
{"_id":"52","_name":"Bình Định","_prefix":"Tỉnh"}, 
{"_id":"54","_name":"Phú Yên","_prefix":"Tỉnh"}, 
{"_id":"56","_name":"Khánh Hòa","_prefix":"Tỉnh"}, 
{"_id":"58","_name":"Ninh Thuận","_prefix":"Tỉnh"}, 
{"_id":"60","_name":"Bình Thuận","_prefix":"Tỉnh"}, 
{"_id":"62","_name":"Kon Tum","_prefix":"Tỉnh"}, 
{"_id":"64","_name":"Gia Lai","_prefix":"Tỉnh"}, 
{"_id":"66","_name":"Đắk Lắk","_prefix":"Tỉnh"}, 
{"_id":"67","_name":"Đắk Nông","_prefix":"Tỉnh"}, 
{"_id":"68","_name":"Lâm Đồng","_prefix":"Tỉnh"}, 
{"_id":"70","_name":"Bình Phước","_prefix":"Tỉnh"}, 
{"_id":"72","_name":"Tây Ninh","_prefix":"Tỉnh"}, 
{"_id":"74","_name":"Bình Dương","_prefix":"Tỉnh"}, 
{"_id":"75","_name":"Đồng Nai","_prefix":"Tỉnh"}, 
{"_id":"77","_name":"Bà Rịa - Vũng Tàu","_prefix":"Tỉnh"}, 
{"_id":"79","_name":"Hồ Chí Minh","_prefix":"Trung ương"}, 
{"_id":"80","_name":"Long An","_prefix":"Tỉnh"}, 
{"_id":"82","_name":"Tiền Giang","_prefix":"Tỉnh"}, 
{"_id":"83","_name":"Bến Tre","_prefix":"Tỉnh"}, 
{"_id":"84","_name":"Trà Vinh","_prefix":"Tỉnh"}, 
{"_id":"86","_name":"Vĩnh Long","_prefix":"Tỉnh"}, 
{"_id":"87","_name":"Đồng Tháp","_prefix":"Tỉnh"}, 
{"_id":"89","_name":"An Giang","_prefix":"Tỉnh"}, 
{"_id":"91","_name":"Kiên Giang","_prefix":"Tỉnh"}, 
{"_id":"92","_name":"Cần Thơ","_prefix":"Trung ương"}, 
{"_id":"93","_name":"Hậu Giang","_prefix":"Tỉnh"}, 
{"_id":"94","_name":"Sóc Trăng","_prefix":"Tỉnh"}, 
{"_id":"95","_name":"Bạc Liêu","_prefix":"Tỉnh"}, 
{"_id":"96","_name":"Cà Mau","_prefix":"Tỉnh"}]

export default initialProvince;